version: "3.8"

networks:
  monitor-net:
    driver: bridge

services:
  ######################################################################################
  #####################           POIFIER CONTAINER              #######################
  ######################################################################################

  poifier:
    image: grassets/poifier-client:v2.0.3
    container_name: poifier
    command:
      - "--poifier-server=https://goerli.poifier.io"
      - "--graph-node-status-endpoint=http://index-node-0:8030/graphql"
      - "--mnemonic=${OPERATOR_SEED_PHRASE}"
      - "--indexer-address=${STAKING_WALLET_ADDRESS}"
      - "--indexer-agent-epoch-subgraph-endpoint=${INDEXER_AGENT_EPOCH_SUBGRAPH_ENDPOINT:-https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle}"
    tty: true
    networks:
      - monitor-net
    restart: unless-stopped

  ######################################################################################
  #####################            INDEXER AGENT GUI             #######################
  ######################################################################################

  indexer-agent-gui:
    image: ${INDEXER_AGENT_GUI:-ghcr.io/stakemachine/indexer-agent-ui:v0.2.1}
    container_name: indexer-agent-gui
    expose:
      - 3000
    environment:
      - UI_LOGIN=${ADMIN_USER:-test}
      - UI_PASS=${ADMIN_PASSWORD:-pass}
      - AGENT_ENDPOINT=${INDEXER_AGENT_ENDPOINT:-http://indexer-agent:8000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${AGENT_GUI_HOST}/
      - SUBGRAPH_ENDPOINT=${INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT:-https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-goerli}
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.indexer-agent-gui.loadbalancer.server.port=3000"
      - "traefik.http.routers.indexer-agent-gui.entrypoints=websecure"
      - "traefik.http.routers.indexer-agent-gui.tls.certresolver=myresolver"
      - "traefik.http.routers.indexer-agent-gui.rule=Host(`$AGENT_GUI_HOST`)"

 