---
apiVersion: 1
datasources:
  - access: proxy
    editable: true
    name: graphql
    orgId: 1
    type: yesoreyeram-infinity-datasource
    url: https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-testnet
    version: 1
