{
 "title": "Deployment details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "query": "select distinct split_part(name, '/', 1) from subgraphs.subgraph order by 1;"
   },
   {
    "name": "deployment",
    "label": "Deployment ID",
    "query": "select\n  g.name || (case\n        when g.pending_version = v.id then ' (P)'\n        when g.current_version = v.id then ' (C)'\n        else ' (U)' end) as __text,\n  ds.subgraph as __value\nfrom deployment_schemas as ds,\n     subgraphs.subgraph_deployment_assignment as a,\n     subgraphs.subgraph_version as v,\n     subgraphs.subgraph as g\nwhere g.id = v.subgraph\n  and v.id in (g.pending_version, g.current_version)\n  and a.id = ds.id\n  and v.deployment = ds.subgraph\n  and g.name like '[[account]]/%'\n"
   },
   { "name": "shard", "query": "postgres" },
   {
    "name": "horizon",
    "label": "Indexing metrics horizon",
    "query": "select 'since deploy' __text, '1y' as __value\nunion all\nselect 'last 24 hours' __text, '1d' as __value\nunion all\nselect 'last 12 hours' __text, '12h' as __value\nunion all\nselect 'last 6 hours' __text, '6h' as __value\nunion all\nselect 'last 3 hours' __text, '3h' as __value\nunion all\nselect 'last 1 hour' __text, '1h' as __value"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary (primary)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with d as\n (select ds.subgraph as id,\n         (select n.head_block_number\n            from ethereum_networks n\n           where n.name = ds.network) as ethereum_head_block_number,\n         ds.network,\n         (select a.node_id from subgraphs.subgraph_deployment_assignment a\n           where a.id = ds.id) as node_id,\n         ds.shard as shard\n    from deployment_schemas ds\n   where ds.subgraph = '[[deployment]]')\nselect 'ID' as name, d.id as value from d\n union all\nselect 'Network', d.network::text from d\n union all\nselect 'Chain head block',\n       to_char(d.ethereum_head_block_number, '999G999G999G999') from d\n union all\nselect 'Indexing node', d.node_id::text from d\n union all\nselect 'Shard', d.shard from d\n"
    }
   ]
  },
  {
   "title": "Time spent while indexing",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\"}[$horizon]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (stage) (increase(deployment_sync_secs{deployment=\"[[deployment]]\"}[$horizon]))",
     "legendFormat": "stage: {{stage}}"
    },
    {
     "expr": "sum by (section, stage) (increase(deployment_sync_secs{deployment=\"[[deployment]]\"}[$horizon]))",
     "legendFormat": "{{section}} [{{stage}}]"
    }
   ]
  },
  {
   "title": "Summary (shard)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "with d as\n (select d.failed,\n         d.synced,\n         d.earliest_block_number,\n         d.latest_ethereum_block_number,\n         d.entity_count,\n         d.health\n    from subgraphs.subgraph_deployment d\n    where d.deployment = '[[deployment]]')  \nselect 'Health', d.health::text from d\n union all\nselect 'Synced', d.synced::text from d\n union all\nselect 'Earliest processed ethereum block',\n       to_char(d.earliest_block_number, '999G999G999G999') from d\n union all\nselect 'Latest processed ethereum block',\n       to_char(d.latest_ethereum_block_number, '999G999G999G999') from d\n union all\nselect 'Entity count', d.entity_count::text from d\n"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(query_execution_time_count{deployment=\"[[deployment]]\"}[1m]))",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  },
  {
   "title": "Total request duration per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(query_execution_time_bucket{deployment=\"[[deployment]]\"}[1m]))*1000",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  },
  {
   "title": "Sections over time (process)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (section) (increase(deployment_sync_secs{deployment=\"[[deployment]]\",stage=\"process\"}[5m]))/300",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Sections over time (writer)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (section) (increase(deployment_sync_secs{deployment=\"[[deployment]]\",stage=\"writer\"}[5m]))/300",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Blocks Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(deployment_block_processing_duration_count{deployment=\"[[deployment]]\"}[1m])/rate(deployment_block_processing_duration_sum{deployment=\"[[deployment]]\"}[1m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(deployment_block_processing_duration_sum{deployment=\"[[deployment]]\"}[1m]))/sum(rate(deployment_block_processing_duration_count{deployment=\"[[deployment]]\"}[1m]))",
     "legendFormat": "deployment"
    }
   ]
  }
 ]
}