{
 "title": "Indexing Performance Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": {
     "query": "label_values(deployment_head,deployment)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(ethereum_chain_head_number,network)"
    }
   },
   {
    "name": "shard",
    "query": {
     "query": "label_values(deployment_head,shard)"
    }
   },
   {
    "name": "provider",
    "query": {
     "query": "label_values(deployment_eth_rpc_request_duration,provider)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Individual subgraph sync rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "deriv(deployment_head{deployment=~\"$deployment\", network=~\"$network\", shard=~\"$shard\"}[10m]) * 60",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "All subgraphs sync rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(deriv(deployment_head[10m]) * 60)",
     "legendFormat": "Total Sync Rate"
    }
   ]
  },
  {
   "title": "Blocks behind over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "abs(deployment_head{deployment=~\"$deployment\", network=~\"$network\", shard=~\"$shard\"} - on (network) group_left max by (network) (ethereum_chain_head_number))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Eth RPC Request Duration per Subgraph",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(deployment_eth_rpc_request_duration{deployment=~\"$deployment\", provider=~\"$provider\"}[15m])",
     "legendFormat": "{{ deployment }} | {{ provider }} | {{ method }}"
    }
   ]
  },
  {
   "title": "Eth RPC Errors per minute (all subgraphs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(eth_rpc_errors{provider=~\"$provider\", job=~\"$job\"}[1m])*60",
     "legendFormat": "{{entity}} | {{provider}} | {{method}}"
    }
   ]
  }
 ]
}