{
 "title": "Graphcast Subgraph Radio",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Comparison Results",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "groupBy": "resultType",
     "queryText": "query {\n  data:comparisonResults{\n    deployment\n    resultType\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Message averages",
   "type": "bargauge",
   "description": "Average metrics based on each scrape\n- counter for received valid messages\n- gauge of cached messages\n\n- cached messages \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(graphcast_subgraph_radio_validated_messages{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(graphcast_subgraph_radio_cached_ppoi_messages{})"
    },
    {
     "expr": "avg(graphcast_subgraph_radio_local_ppois_to_compare{})"
    }
   ]
  },
  {
   "title": "Result Aggregation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "groupBy": "null",
     "queryText": "query {\n  data:comparisonRatio{\n    deployment\n    blockNumber\n    senderRatio\n    stakeRatio\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Locally tracked Public POIs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_local_ppois_to_compare"
    }
   ]
  },
  {
   "title": "Number of active peer indexers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_ACTIVE_INDEXERS"
    }
   ]
  },
  {
   "title": "Rate of receiving messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(graphcast_subgraph_radio_cached_ppoi_messages[5m])"
    }
   ]
  },
  {
   "title": "Number of diverged subgraphs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_diverging_subgraphs"
    }
   ]
  },
  {
   "title": "Function Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "function_calls_concurrent" },
    {
     "expr": "histogram_quantile(0.95, sum(rate(function_calls_duration_bucket[5m])) by (le))"
    },
    { "expr": "rate(function_calls_count[5m])" }
   ]
  }
 ]
}